Sonar issues 92
imsweb/mph pull request #95
Opened 2023-03-29 23:28 UTC by bekeles

2023-03-30 11:59 UTC, bekeles commented
closes #92 

Fabian I fixed the major issues reported by sonar. I am not sure if we need a change log for this or not.

2023-03-30 12:09 UTC, depryf requested changes

2023-03-30 12:09 UTC, depryf commented on src/main/java/com/imsweb/mph/MphConstants.java
> +    private static final String EPENDYMOMAS = "Ependymomas";
Private static should start with an underscore.

2023-03-30 12:10 UTC, depryf commented
Just a minor thing. No need of a changelog entry for this type of code cleanup.

2023-03-31 12:57 UTC, bekeles commented
@depryf I know you are busy, I just don't want this to slip away from your way :)

2023-03-31 13:05 UTC, merged